# Server
server:
  port: 8080

# Database H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # Manual table creation not Hibernate
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always  # Always initialize the database
      schema-locations: classpath:initDB.sql  # Create the tables
      data-locations: classpath:products.sql  # Insert data

# SpringDoc OpenAPI (Swagger)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs